name: Environment Variables Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      env:
        type: environment

env:
  WORKFLOW_VARIABLE: WORKFLOW

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: JOB
    steps:
      - name: Run Commands with various variables
        if: ${{ env.WORKFLOW_VARIABLE == 'WORKFLOW' }} # Example using context env
        env:
          STEP_VARIABLE: STEP
        run: |
          echo "Hello World"
          echo "This is the $WORKFLOW_VARIABLE environment variable"
          echo "This is the $JOB_VARIABLE environment variable"
          echo "This is the $STEP_VARIABLE environment variable"
          
  get-build-number1:
    environment: teste
    runs-on: ubuntu-latest
    steps:
    - name: Output Run ID1
      run: "echo ${{ vars.ENV_VAR }}"
    - name: Output Run Number
      run: echo ${{ secrets.REPO_SE }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
